# Generated by Django 2.1.7 on 2019-03-26 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4194304)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tm.Corpus')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FilePathField(verbose_name='/home/results_files')),
                ('topic_num', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('method', models.CharField(choices=[('LDA', 'Latent Dirichlet Allocation'), ('PA', 'Pachinko'), ('CTM', 'Correlated Topic Model')], max_length=3)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tm.Corpus')),
            ],
        ),
    ]
